### PR TITLE
fix coloring for selected rows on selectable tables

### PR DESCRIPTION
**Pull request by josephcrowell**
This fixes the coloring for selected rows on tables that allow row selection, such as the event log.

### CODE REVIEW

**Comment by josephcrowell** [comment]
Before
image

**Comment by josephcrowell** [comment]
After
image

**Comment by LukeTowers** [comment]
Need the production compiled css included in the pr too please :)

**Comment by josephcrowell** [comment]
Done :)

**Comment by josephcrowell** [comment]
Arg it's not minified

**Review by LukeTowers — APPROVED** [review]

**Pull request merged**
