### PR TITLE
updates to tailwind 3.2 + adds missing dark mode colors

### PR DESCRIPTION
**Pull request by der-On**
This updates tailwind to version 3.2 and adds some missing dark mode colors that work well with the [dark backend plugin](https://github.com/WebVPF/wn-darkbackend-plugin).

Note:

had to rename the class `collapse` to `collapsible`  in the side menu as `collapse` is already used by tailwindcss https://tailwindcss.com/docs/visibility#collapsing-elements

### CODE REVIEW

**Comment by damsfx** [comment]
I'm a big fan of dark interfaces (I use them wherever possible), but this PR leaves me confused on two points.

**First** : I don't see the point of adding an extra dependency through a plugin.  
What this plugin offers should be present in this plugin.

**Second thing** : the [dark backend plugin](https://github.com/WebVPF/wn-darkbackend-plugin) plugin does not take into account the user's preference and only offers two modes, light or dark, it lacks a third state which is based on the user's preference:
`window .matchMedia('(preferences-color-scheme: dark)')`
or
`document.querySelector('meta[name="color-scheme"]') ` (which is not my preference).

What is your feeling about it?

**Comment by damsfx** [comment]
To argue my point number one: 

The [dark backend plugin](https://github.com/WebVPF/wn-darkbackend-plugin) seeks to add through a script an item in the user menu using 
```javascript
document.querySelector('.mainmenu-accountmenu li.divider').before(toggleTheme);
```
See : https://github.com/WebVPF/wn-darkbackend-plugin/blob/52bdb5c44490a43431988c5486a39decb2b3ce47/assets/js/script.js#L26

But the `.mainmenu-accountmenu` selector does not exist in the Tailwind backend theme.

**Comment by der-On** [comment]
At the moment the dark backend plugin is the only one I know that allows to use at least a dark mode in winter backend. If this plugin should provide it, then I can make a PR for that. But I would recommend to use the `media` darkMode of tailwind instead of the `class` dark mode which I basically just made work in my PR even without the dark backend plugin. Tailwind's class based dark mode requires a `.dark` class to be up in the DOM tree for the `dark:...` selectors to work.

**Comment by der-On** [comment]
A fully working dark mode based on user preferences and not a `.dark` class would also mean alot of additional css to make all existing UI dark. The dark backend plugin already contains a lot of this that could be taken/borrowed and build upon.

**Comment by LukeTowers** [comment]
Closing in favour of #23

**Pull request closed without merging**
